services:
  mysql:
    image: 'mysql:latest'
    environment:
      - 'MYSQL_DATABASE=crudcursos'
      - 'MYSQL_PASSWORD=123456'
      - 'MYSQL_ROOT_PASSWORD=verysecret'
      - 'MYSQL_USER=marco'
    ports:
      - '3307:3306'
  redis:
    image: 'redis:7.0.5-alpine'
    restart: always
    ports:
      - '6379:6379'
